name: "CO₂ Electrocatalyst Descriptor Discovery"
description: "Autonomous discovery of high-performance CO₂ reduction electrocatalysts"
batch_size: 12
per_task_timeout: 900  # 15 minutes for DFT calculations
priority: high

# Discovery objective
objective: "maximize_FE_at_50mAcm2"
target_metrics:
  faradaic_efficiency_CO: {">=": 85}
  current_density_mAcm2: {">=": 50}
  stability_hours: {">=": 24}
  overpotential_V: {"<=": 0.8}

# FoT virtue weighting
virtue_weighting:
  Beneficence: 0.7    # Climate change mitigation impact
  Prudence: 0.2       # Energy efficiency and cost considerations  
  Honesty: 0.1        # Transparent performance reporting

# Data sources for catalyst discovery
sources:
  - type: literature-watch
    description: "Monitor latest CO₂ reduction research"
    keywords: ["CO2 reduction", "electrocatalyst", "copper", "silver", "faradaic efficiency"]
    sources: ["pubmed", "web_of_science", "materials_project"]
    min_relevance: 0.85
    
  - type: materials-database
    description: "Monitor materials databases for new entries"
    apis:
      - "materials_project"
      - "aflow"
      - "catalysis_hub"
    update_frequency: "daily"
    
  - type: experimental-reports
    description: "Monitor experimental data repositories"
    sources: ["open_catalyst_project", "electrocatalysis_database"]
    data_types: ["performance_metrics", "dft_calculations"]

# Catalyst generation strategy  
generator:
  type: "descriptor_bayesian_optimization"
  
  # Search space definition
  search_space:
    metal_elements: ["Cu", "Ag", "Au", "Pd", "Pt", "Ni", "Co", "Fe"]
    support_materials: ["carbon", "graphene", "cnt", "oxide_supports"]
    surface_facets: ["100", "111", "110", "211"]
    defect_types: ["vacancy", "step", "kink", "grain_boundary"]
    
  # Descriptor space
  descriptors:
    electronic:
      - d_band_center_eV
      - work_function_eV  
      - electronegativity
      - electron_affinity
      
    geometric:
      - coordination_number
      - surface_area_m2g
      - pore_size_distribution
      - active_site_density
      
    energetic:
      - co_binding_energy_eV
      - h_binding_energy_eV
      - cho_binding_energy_eV
      - cooh_binding_energy_eV
      
  # Optimization parameters
  acquisition_function: "upper_confidence_bound"
  kernel: "matern52"
  initial_design: "latin_hypercube"
  initial_samples: 20
  exploration_weight: 0.1

# Computational measurement protocols
measure:
  # DFT calculations
  quantum_chemistry:
    - kind: "dft_adsorption_energies"
      description: "Calculate binding energies for key intermediates"
      method: "PBE_PAW"
      basis_set: "400eV_cutoff"
      kpoints: "4x4x1"
      convergence: "1e-5_eV"
      
    - kind: "surface_stability"
      description: "Evaluate catalyst stability under operating conditions"
      method: "ab_initio_thermodynamics"
      conditions: {"pH": 7, "potential_V": -1.0, "temperature_K": 298}
      
  # Property predictions
  properties:
    - faradaic_efficiency_CO
    - faradaic_efficiency_formate  
    - faradaic_efficiency_ethylene
    - current_density_mAcm2
    - overpotential_V
    - stability_cycles
    
  # Microkinetic modeling
  kinetics:
    - kind: "microkinetic_simulation"
      description: "Predict selectivity and rates from elementary steps"
      solver: "steady_state_approximation" 
      temperature_range: [273, 323]
      potential_range: [-0.5, -1.5]

# Performance thresholds for truth collapse
collapse_rules:
  success_criteria:
    faradaic_efficiency_CO: {">=": 85}
    current_density_mAcm2: {">=": 50} 
    stability_hours: {">=": 24}
    dft_convergence: {"<=": 0.001}  # eV convergence
    replication_agreement: {">=": 2}
    
  uncertainty_thresholds:
    max_fe_uncertainty: 5  # % absolute
    max_binding_energy_uncertainty: 0.1  # eV
    min_model_confidence: 0.8
    
  statistical_requirements:
    min_sample_size: 8
    cross_validation_r2: {">=": 0.7}
    outlier_threshold: 2  # standard deviations

# Safety and ethics for catalysts
ethics:
  # Safe metal constraints
  allowed_metals:
    - "Cu"  # Earth abundant, non-toxic
    - "Ag"  # Low toxicity, good performance
    - "Ni"  # Industrial catalyst, established safety
    - "Co"  # Acceptable in controlled applications
    - "Fe"  # Earth abundant, non-toxic
    
  # Restricted elements (high toxicity/cost)
  restricted_metals:
    - "Hg"  # Highly toxic
    - "Cd"  # Carcinogenic
    - "Pb"  # Toxic heavy metal
    - "As"  # Toxic metalloid
    
  # Performance vs sustainability trade-offs
  sustainability_weighting:
    earth_abundance: 0.4
    toxicity_score: 0.3
    recyclability: 0.2
    energy_efficiency: 0.1
    
  # Output restrictions
  publication_constraints:
    no_synthesis_details: true
    descriptors_only: true
    safety_data_required: true
    lca_estimates_preferred: true

# Environmental and economic constraints
practical_considerations:
  cost_targets:
    catalyst_cost_per_gram: {"<": 50}  # USD/g
    preparation_complexity: {"<": 7}   # Scale 1-10
    
  stability_requirements:
    operating_temperature_max: 80  # Celsius
    ph_stability_range: [6, 14]
    corrosion_resistance: "high"
    
  scalability_factors:
    metal_abundance_score: {">=": 0.6}
    manufacturing_readiness: {">=": 5}  # TRL scale
    supply_chain_risk: {"<": 0.3}

# Discovery campaign tracking
metadata:
  version: "1.0"
  created: "2025-09-28"
  focus_area: "carbon_utilization"
  impact_category: "climate_change_mitigation"
  
  benchmarks:
    - "copper_foil_baseline"
    - "silver_nanoparticles_reference"
    - "literature_best_performers"
    
  related_initiatives:
    - "02_co2_electrocatalysts"
    - "carbon_negative_chemistry"
    - "renewable_energy_storage"

# Expected performance and timeline
projections:
  discovery_timeline: "8-12 weeks"
  candidate_generation_rate: "5-8 per week"
  experimental_validation_rate: "2-3 per week"
  truth_collapse_probability: 0.7
  
  success_indicators:
    breakthrough_fe_threshold: 90  # % CO
    commercial_viability_score: {">=": 0.8}
    community_adoption_likelihood: "high"

# Reporting configuration
reporting:
  public_leaderboard: true
  weekly_progress_updates: true
  performance_benchmarking: true
  uncertainty_quantification: "always"
  
dashboard_metrics:
  - "top_10_performers_by_FE"
  - "pareto_front_fe_vs_stability" 
  - "descriptor_importance_ranking"
  - "discovery_rate_over_time"
  
archival:
  dft_output_files: true
  calculation_logs: true
  convergence_criteria: true
  container_environments: true
