version: '3.8'

services:
  # Neo4j Knowledge Graph Database
  neo4j:
    image: neo4j:5.13-community
    container_name: fotchem-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/fotchemistry123
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial_size=1G
      - NEO4J_dbms_memory_heap_max_size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_default_listen_address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen_address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen_address=0.0.0.0:7474
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./seeds:/seeds:ro
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "fotchemistry123", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # GraphDB RDF Triplestore
  graphdb:
    image: ontotext/graphdb:10.4.1
    container_name: fotchem-graphdb
    restart: unless-stopped
    ports:
      - "7200:7200"  # HTTP interface
    environment:
      - GDB_HEAP_SIZE=2G
      - GDB_JAVA_OPTS=-Xmx2g -Xms1g
    volumes:
      - graphdb_data:/opt/graphdb/home
      - graphdb_work:/opt/graphdb/work
      - ./seeds:/seeds:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/rest/repositories"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # SPARQL Endpoint (Fuseki)
  fuseki:
    image: stain/jena-fuseki:4.9.0
    container_name: fotchem-fuseki
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=fotchem123
      - JVM_ARGS=-Xmx2g -Xms1g
    volumes:
      - fuseki_data:/fuseki
      - ./seeds:/seeds:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis for caching and session management
  redis:
    image: redis:7.2-alpine
    container_name: fotchem-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass fotchem123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  # MinIO for object storage (datasets, exports)
  minio:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    container_name: fotchem-minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=fotchem
      - MINIO_ROOT_PASSWORD=fotchemistry123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Jupyter Lab for interactive development
  jupyter:
    image: jupyter/scipy-notebook:2023-10-20
    container_name: fotchem-jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=fotchem123
    volumes:
      - jupyter_data:/home/jovyan/work
      - ../:/home/jovyan/work/fotchemistry:ro
    working_dir: /home/jovyan/work
    user: root
    command: >
      bash -c "
        pip install rdkit neo4j rdflib owlready2 &&
        start-notebook.sh --NotebookApp.token='fotchem123' --NotebookApp.password='' --ip=0.0.0.0 --port=8888 --allow-root
      "

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  graphdb_data:
    driver: local
  graphdb_work:
    driver: local
  fuseki_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  jupyter_data:
    driver: local

networks:
  default:
    name: fotchem-network
    driver: bridge
