[global]
# Configuration for Streamlit Cloud
dataFrameSerialization = "legacy"

[server]
# Performance settings for cloud deployment
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[theme]
# FoTChemistry theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"